// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaVeM179LG1-knd1nkTOh0aP6bzyQD-Jk',
    appId: '1:436400102177:web:3732c1333465f50bf7bc60',
    messagingSenderId: '436400102177',
    projectId: 'evently-1a443',
    authDomain: 'evently-1a443.firebaseapp.com',
    storageBucket: 'evently-1a443.firebasestorage.app',
    measurementId: 'G-XGR5C5F6L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMoWk-tbi_yCYTWBIO6hHObbypzZEYqzA',
    appId: '1:436400102177:android:5c0a8f5b3b4c70aaf7bc60',
    messagingSenderId: '436400102177',
    projectId: 'evently-1a443',
    storageBucket: 'evently-1a443.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1-L_VwJn3tpiYpTzD7BJ6uVWA-_WjQOQ',
    appId: '1:436400102177:ios:ca9b5a3083fc6f76f7bc60',
    messagingSenderId: '436400102177',
    projectId: 'evently-1a443',
    storageBucket: 'evently-1a443.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1-L_VwJn3tpiYpTzD7BJ6uVWA-_WjQOQ',
    appId: '1:436400102177:ios:ca9b5a3083fc6f76f7bc60',
    messagingSenderId: '436400102177',
    projectId: 'evently-1a443',
    storageBucket: 'evently-1a443.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanningapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaVeM179LG1-knd1nkTOh0aP6bzyQD-Jk',
    appId: '1:436400102177:web:e8329229cd13ff7ef7bc60',
    messagingSenderId: '436400102177',
    projectId: 'evently-1a443',
    authDomain: 'evently-1a443.firebaseapp.com',
    storageBucket: 'evently-1a443.firebasestorage.app',
    measurementId: 'G-YT2ZMT1D1N',
  );
}
